/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.prog2.labs;

import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author Amer-
 */
public class ContentForm extends javax.swing.JFrame {

    private ResourceBundle bundle;
    private ResourceBundle bundleFR;
    private Library library;
    private MainForm mainForm;
    private boolean flag;

    /**
     * Creates new form ContentForm
     */
    public ContentForm() {
        initComponents();

        bundle = ResourceBundle.getBundle("FormLanguage");
        bundleFR = ResourceBundle.getBundle("FormLanguage", new Locale("fr", "FR"));
    }

    public ContentForm(MainForm mainForm, boolean librarian) {
        initComponents();
        this.mainForm = mainForm;

        bundle = ResourceBundle.getBundle("FormLanguage");
        bundleFR = ResourceBundle.getBundle("FormLanguage", new Locale("fr", "FR"));

        if (librarian == true) {
            setVisible(true);
            borrowButton.setText("Issue a Book");
            searchTitleLabel.enable(false);
            searchTitleTextField.enable(false);
            searchAuthorLabel.enable(false);
            searchAuthorTextField.enable(false);
            searchPublisherLabel.enable(false);
            searchPublisherTextField.enable(false);
            searchButton.enable(false);
            flag = true;
        } else {
            setVisible(true);
            borrowButton.setText("Borrow");
            serialLabel.enable(false);
            serialTextField.enable(false);
            titleLabel.enable(false);
            titleTextField.enable(false);
            authorLabel.enable(false);
            authorTextField.enable(false);
            publisherLabel.enable(false);
            publisherTextField.enable(false);
            priceLabel.enable(false);
            priceTextField.enable(false);
            quantityLabel.enable(false);
            quantityTextField.enable(false);
            bookButton.enable(false);
            flag = false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchTitleLabel = new javax.swing.JLabel();
        searchTitleTextField = new javax.swing.JTextField();
        studentNameLabel = new javax.swing.JLabel();
        searchAuthorLabel = new javax.swing.JLabel();
        studentNameTextField = new javax.swing.JTextField();
        searchAuthorTextField = new javax.swing.JTextField();
        bookTitleLabel = new javax.swing.JLabel();
        searchPublisherLabel = new javax.swing.JLabel();
        bookTitleTextField = new javax.swing.JTextField();
        searchPublisherTextField = new javax.swing.JTextField();
        borrowButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        statusTextArea = new javax.swing.JScrollPane();
        borrowStatusTextArea = new javax.swing.JTextArea();
        statusTextArea1 = new javax.swing.JScrollPane();
        bookStatusTextArea = new javax.swing.JTextArea();
        returnButton = new javax.swing.JButton();
        publisherLabel = new javax.swing.JLabel();
        publisherTextField = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        serialLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        serialTextField = new javax.swing.JTextField();
        quantityLabel = new javax.swing.JLabel();
        bookButton = new javax.swing.JButton();
        quantityTextField = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        catalogTextArea = new javax.swing.JTextArea();
        titleTextField = new javax.swing.JTextField();
        authorLabel = new javax.swing.JLabel();
        viewIssuedBooksButton = new javax.swing.JButton();
        authorTextField = new javax.swing.JTextField();
        viewBooksButton = new javax.swing.JButton();
        englishRadioButton = new javax.swing.JRadioButton();
        frenchRadioButton = new javax.swing.JRadioButton();
        mainButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(958, 699));

        searchTitleLabel.setText("Book Title :");
        searchTitleLabel.setName("authorLabel"); // NOI18N

        searchTitleTextField.setName("bookAuthor"); // NOI18N

        studentNameLabel.setText("Student Name :");
        studentNameLabel.setName("nameLabel"); // NOI18N

        searchAuthorLabel.setText("Book Author :");
        searchAuthorLabel.setName("titleLabel"); // NOI18N

        studentNameTextField.setName("nameTextField"); // NOI18N

        searchAuthorTextField.setName("bookTitle"); // NOI18N

        bookTitleLabel.setText("Book Title :");
        bookTitleLabel.setName("nameLabel"); // NOI18N

        searchPublisherLabel.setText("Book Year of Publishment :");
        searchPublisherLabel.setName("authorLabel"); // NOI18N

        bookTitleTextField.setName("nameTextField"); // NOI18N

        searchPublisherTextField.setName("bookAuthor"); // NOI18N

        borrowButton.setText("Borrow");
        borrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.setToolTipText("");
        searchButton.setName("addBook"); // NOI18N
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        borrowStatusTextArea.setColumns(20);
        borrowStatusTextArea.setRows(5);
        statusTextArea.setViewportView(borrowStatusTextArea);

        bookStatusTextArea.setColumns(20);
        bookStatusTextArea.setRows(5);
        statusTextArea1.setViewportView(bookStatusTextArea);

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        publisherLabel.setText("Publisher :");
        publisherLabel.setName("authorLabel"); // NOI18N

        publisherTextField.setName("bookAuthor"); // NOI18N

        priceLabel.setText("Price :");
        priceLabel.setName("authorLabel"); // NOI18N

        priceTextField.setName("bookAuthor"); // NOI18N

        serialLabel.setText("Serial Number :");
        serialLabel.setName("authorLabel"); // NOI18N

        welcomeLabel.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        welcomeLabel.setText("Welcome to Library");

        serialTextField.setName("bookAuthor"); // NOI18N

        quantityLabel.setText("Quantity :");
        quantityLabel.setName("authorLabel"); // NOI18N

        bookButton.setText("Add Book");
        bookButton.setToolTipText("");
        bookButton.setName("addBook"); // NOI18N
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });

        quantityTextField.setName("bookAuthor"); // NOI18N

        titleLabel.setText("Title :");
        titleLabel.setName("titleLabel"); // NOI18N

        catalogTextArea.setColumns(20);
        catalogTextArea.setRows(5);
        jScrollPane1.setViewportView(catalogTextArea);

        titleTextField.setName("bookTitle"); // NOI18N

        authorLabel.setText("Author :");
        authorLabel.setName("authorLabel"); // NOI18N

        viewIssuedBooksButton.setText("View Issued Books");
        viewIssuedBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewIssuedBooksButtonActionPerformed(evt);
            }
        });

        authorTextField.setName("bookAuthor"); // NOI18N

        viewBooksButton.setText("View All Books");
        viewBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBooksButtonActionPerformed(evt);
            }
        });

        englishRadioButton.setText("English");
        englishRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishRadioButtonActionPerformed(evt);
            }
        });

        frenchRadioButton.setText("French");
        frenchRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frenchRadioButtonActionPerformed(evt);
            }
        });

        mainButton.setText("Back to Main Page");
        mainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(mainButton)
                .addContainerGap(771, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(studentNameLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(studentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bookTitleLabel)
                                            .addComponent(borrowButton)
                                            .addComponent(returnButton))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(bookTitleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                            .addComponent(statusTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                                .addComponent(bookButton)
                                .addComponent(authorLabel)
                                .addComponent(titleLabel)
                                .addComponent(publisherLabel)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(quantityLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                                        .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(priceLabel)
                                            .addComponent(serialLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(serialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(publisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(statusTextArea1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(searchPublisherLabel)
                                        .addComponent(searchAuthorLabel)
                                        .addComponent(searchTitleLabel))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(searchTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchAuthorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchPublisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(viewBooksButton)
                                    .addGap(28, 28, 28)
                                    .addComponent(viewIssuedBooksButton))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(searchButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(frenchRadioButton)
                                            .addComponent(englishRadioButton)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(248, 248, 248)
                            .addComponent(welcomeLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(61, 61, 61)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(mainButton)
                .addContainerGap(626, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(welcomeLabel)
                                    .addGap(37, 37, 37)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(serialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(serialLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(titleLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(authorLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(publisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(publisherLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(priceLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(quantityLabel))
                                    .addGap(18, 18, 18)
                                    .addComponent(bookButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(statusTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(viewIssuedBooksButton)
                                        .addComponent(viewBooksButton))
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(searchTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchTitleLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(searchAuthorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchAuthorLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(searchPublisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchPublisherLabel))
                                    .addGap(18, 18, 18)
                                    .addComponent(searchButton)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(459, 459, 459)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(studentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(studentNameLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bookTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bookTitleLabel))
                                    .addGap(42, 42, 42)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(borrowButton)
                                            .addGap(18, 18, 18)
                                            .addComponent(returnButton))
                                        .addComponent(statusTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(englishRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(frenchRadioButton)))))
                    .addGap(40, 40, 40)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Borrows book from database
     * @param evt 
     */
    private void borrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowButtonActionPerformed
        if (flag) {
            borrowStatusTextArea.setText(Controller.getInstance().issueBook());
        } else {
            borrowStatusTextArea.setText(Controller.getInstance().borrowBook());
        }
    }//GEN-LAST:event_borrowButtonActionPerformed

    /**
     * Searches for book from database
     * @param evt 
     */
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String title = searchTitleTextField.getText();
        String author = searchAuthorTextField.getText();
        String publisher = searchPublisherTextField.getText();

        if (!title.equals("") && author.equals("") && publisher.equals("")) {
            catalogTextArea.setText(Controller.getInstance().searchBooksByTitle(title));
        } else if (title.equals("") && !author.equals("") && publisher.equals("")) {
            catalogTextArea.setText(Controller.getInstance().searchBooksByAuthor(author));
        } else if (title.equals("") && author.equals("") && !publisher.equals("")) {
            catalogTextArea.setText(Controller.getInstance().searchBooksByPublisher(publisher));
        } else {
            catalogTextArea.setText("You can only search for one field at a time!");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * Returns book from database
     * @param evt 
     */
    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        if (flag) {
            borrowStatusTextArea.setText(Controller.getInstance().issueReturn());
        } else {
            borrowStatusTextArea.setText(Controller.getInstance().returnBook());
        }
    }//GEN-LAST:event_returnButtonActionPerformed

    /**
     * Add a book to the database
     * @param evt 
     */
    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        bookStatusTextArea.setText(Controller.getInstance().addBook());
    }//GEN-LAST:event_bookButtonActionPerformed

    /**
     * Translates text to english
     * @param evt 
     */
    private void englishRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishRadioButtonActionPerformed
        frenchRadioButton.setSelected(false);
        mainButton.setText(bundle.getString("BackToMainPage"));
        welcomeLabel.setText(bundle.getString("WelcometoLibrary"));
        serialLabel.setText(bundle.getString("SN"));
        titleLabel.setText(bundle.getString("Title"));
        authorLabel.setText(bundle.getString("Author"));
        publisherLabel.setText(bundle.getString("Publisher"));
        priceLabel.setText(bundle.getString("Price"));
        quantityLabel.setText(bundle.getString("Quantity"));
        bookButton.setText(bundle.getString("AddBook"));
        viewBooksButton.setText(bundle.getString("ViewAllBooks"));
        viewIssuedBooksButton.setText(bundle.getString("ViewIssuedBooks"));
        searchTitleLabel.setText(bundle.getString("BookTitle"));
        searchPublisherLabel.setText(bundle.getString("BookYearOfPublishment"));
        searchAuthorLabel.setText(bundle.getString("BookAuthor"));
        studentNameLabel.setText(bundle.getString("StudentName"));
        searchButton.setText(bundle.getString("Search"));
        englishRadioButton.setText(bundle.getString("English"));
        frenchRadioButton.setText(bundle.getString("French"));
        bookTitleLabel.setText(bundle.getString("BookTitle"));
        if (flag) {
            borrowButton.setText(bundle.getString("IssueaBook"));
        }else{
            borrowButton.setText(bundle.getString("Borrow"));
        }
        returnButton.setText(bundle.getString("Return"));
    }//GEN-LAST:event_englishRadioButtonActionPerformed

    /**
     * Translates text to french
     * @param evt 
     */
    private void frenchRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frenchRadioButtonActionPerformed
        englishRadioButton.setSelected(false);
        mainButton.setText(bundleFR.getString("BackToMainPage"));
        welcomeLabel.setText(bundleFR.getString("WelcometoLibrary"));
        serialLabel.setText(bundleFR.getString("SN"));
        titleLabel.setText(bundleFR.getString("Title"));
        authorLabel.setText(bundleFR.getString("Author"));
        publisherLabel.setText(bundleFR.getString("Publisher"));
        priceLabel.setText(bundleFR.getString("Price"));
        quantityLabel.setText(bundleFR.getString("Quantity"));
        bookButton.setText(bundleFR.getString("AddBook"));
        viewBooksButton.setText(bundleFR.getString("ViewAllBooks"));
        viewIssuedBooksButton.setText(bundleFR.getString("ViewIssuedBooks"));
        searchTitleLabel.setText(bundleFR.getString("BookTitle"));
        searchPublisherLabel.setText(bundleFR.getString("BookYearOfPublishment"));
        searchAuthorLabel.setText(bundleFR.getString("BookAuthor"));
        studentNameLabel.setText(bundleFR.getString("StudentName"));
        searchButton.setText(bundleFR.getString("Search"));
        englishRadioButton.setText(bundleFR.getString("English"));
        frenchRadioButton.setText(bundleFR.getString("French"));
        bookTitleLabel.setText(bundleFR.getString("BookTitle"));
        if (flag) {
            borrowButton.setText(bundleFR.getString("IssueaBook"));
        }else{
            borrowButton.setText(bundleFR.getString("Borrow"));
        }
        returnButton.setText(bundleFR.getString("Return"));
    }//GEN-LAST:event_frenchRadioButtonActionPerformed

    /**
     * Goes back to main form
     * @param evt 
     */
    private void mainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainButtonActionPerformed

        mainForm.showMainForm();
        dispose();
    }//GEN-LAST:event_mainButtonActionPerformed

    /**
     * Views all books in the database
     * @param evt 
     */
    private void viewBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBooksButtonActionPerformed
        catalogTextArea.setText(Controller.getInstance().viewAllBooks());
    }//GEN-LAST:event_viewBooksButtonActionPerformed

    /**
     * Views all issued books in the database
     * @param evt 
     */
    private void viewIssuedBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewIssuedBooksButtonActionPerformed
        catalogTextArea.setText(Controller.getInstance().viewIssuedBooks());
    }//GEN-LAST:event_viewIssuedBooksButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContentForm().setVisible(true);
            }
        });
    }

    /**
     * Sets library Object
     * @param library 
     */
    public void setLibrary(Library library) {
        this.library = library;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel;
    public javax.swing.JTextField authorTextField;
    private javax.swing.JButton bookButton;
    public javax.swing.JTextArea bookStatusTextArea;
    private javax.swing.JLabel bookTitleLabel;
    public javax.swing.JTextField bookTitleTextField;
    private javax.swing.JButton borrowButton;
    public javax.swing.JTextArea borrowStatusTextArea;
    private javax.swing.JTextArea catalogTextArea;
    private javax.swing.JRadioButton englishRadioButton;
    private javax.swing.JRadioButton frenchRadioButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainButton;
    private javax.swing.JLabel priceLabel;
    public javax.swing.JTextField priceTextField;
    private javax.swing.JLabel publisherLabel;
    public javax.swing.JTextField publisherTextField;
    private javax.swing.JLabel quantityLabel;
    public javax.swing.JTextField quantityTextField;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel searchAuthorLabel;
    public javax.swing.JTextField searchAuthorTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchPublisherLabel;
    public javax.swing.JTextField searchPublisherTextField;
    private javax.swing.JLabel searchTitleLabel;
    public javax.swing.JTextField searchTitleTextField;
    private javax.swing.JLabel serialLabel;
    public javax.swing.JTextField serialTextField;
    private javax.swing.JScrollPane statusTextArea;
    private javax.swing.JScrollPane statusTextArea1;
    private javax.swing.JLabel studentNameLabel;
    public javax.swing.JTextField studentNameTextField;
    private javax.swing.JLabel titleLabel;
    public javax.swing.JTextField titleTextField;
    private javax.swing.JButton viewBooksButton;
    private javax.swing.JButton viewIssuedBooksButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
