/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.prog2.labs;

import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author Amer-
 */
public class MainForm extends javax.swing.JFrame {

    private ResourceBundle bundle;
    private ResourceBundle bundleFR;
    private Library library;
    private ContentForm contentForm;
    
    public MainForm() {
        initComponents();
        
        bundle = ResourceBundle.getBundle("FormLanguage");
        bundleFR = ResourceBundle.getBundle("FormLanguage", new Locale("fr", "FR"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        englishRadioButton = new javax.swing.JRadioButton();
        frenchRadioButton = new javax.swing.JRadioButton();
        messageLabel = new javax.swing.JLabel();
        librarianRadioButton = new javax.swing.JRadioButton();
        studentRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        welcomeLabel.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        welcomeLabel.setText("Welcome to Library");

        englishRadioButton.setText("English");
        englishRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishRadioButtonActionPerformed(evt);
            }
        });

        frenchRadioButton.setText("French");
        frenchRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frenchRadioButtonActionPerformed(evt);
            }
        });

        messageLabel.setText("Which type of user are you?");
        messageLabel.setName("authorLabel"); // NOI18N

        librarianRadioButton.setText("Librarian");
        librarianRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarianRadioButtonActionPerformed(evt);
            }
        });

        studentRadioButton.setText("Student");
        studentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frenchRadioButton)
                    .addComponent(englishRadioButton))
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(librarianRadioButton)
                            .addComponent(studentRadioButton)
                            .addComponent(messageLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(welcomeLabel)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(welcomeLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(messageLabel)
                        .addGap(18, 18, 18)
                        .addComponent(librarianRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(studentRadioButton)))
                .addGap(32, 32, 32)
                .addComponent(englishRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(frenchRadioButton)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Translates all text into english
     * @param evt 
     */
    private void englishRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishRadioButtonActionPerformed
        frenchRadioButton.setSelected(false);
        welcomeLabel.setText(bundle.getString("WelcometoLibrary"));
        messageLabel.setText(bundle.getString("TypeOfUser"));
        librarianRadioButton.setText(bundle.getString("Librarian"));
        studentRadioButton.setText(bundle.getString("Student"));
        englishRadioButton.setText(bundle.getString("English"));
        frenchRadioButton.setText(bundle.getString("French"));
    }//GEN-LAST:event_englishRadioButtonActionPerformed

    /**
     * Translates all text into french
     * @param evt 
     */
    private void frenchRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frenchRadioButtonActionPerformed
        englishRadioButton.setSelected(false);
        welcomeLabel.setText(bundleFR.getString("WelcometoLibrary"));
        messageLabel.setText(bundleFR.getString("TypeOfUser"));
        librarianRadioButton.setText(bundleFR.getString("Librarian"));
        studentRadioButton.setText(bundleFR.getString("Student"));
        englishRadioButton.setText(bundleFR.getString("English"));
        frenchRadioButton.setText(bundleFR.getString("French"));
    }//GEN-LAST:event_frenchRadioButtonActionPerformed

    /**
     * Opens the librarian version of the content form
     * @param evt 
     */
    private void librarianRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarianRadioButtonActionPerformed
        contentForm = new ContentForm(this, true);
        Controller.getInstance().setContentFormView(contentForm);
        setVisible(false);
        librarianRadioButton.setSelected(false);
    }//GEN-LAST:event_librarianRadioButtonActionPerformed

    /**
     * Opens the student version of the content form
     * @param evt 
     */
    private void studentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRadioButtonActionPerformed
        contentForm = new ContentForm(this, false);
        Controller.getInstance().setContentFormView(contentForm);
        setVisible(false);
        studentRadioButton.setSelected(false);
    }//GEN-LAST:event_studentRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    
    /**
     * Sets library object
     * @param library 
     */
    public void setLibrary(Library library) {
        this.library = library;
    }
    
    /**
     * Sets the visibility of the main form to true
     */
    public void showMainForm() {
        // Show the MainForm
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton englishRadioButton;
    private javax.swing.JRadioButton frenchRadioButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton librarianRadioButton;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JRadioButton studentRadioButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
